using System.ComponentModel.DataAnnotations;

namespace skyforger.models.creatures
{
    public enum CreatureSubType
    {
        Adlet,
        Aeon,
        Agathion,
        [Display(Name = "Artifice Creation")]
        ArtificeCreation,
        Air,
        Angel,
        Aquatic,
        Archon,
        Asura,
        Augmented,
        Automaton,
        Azata,
        Behemoth,
        Catfolk,
        Chaotic,
        Clockwork,
        Cold,
        Colossus,
        Daemon,
        [Display(Name = "Dark Folk")]
        DarkFolk,
        [Display(Name = "Deep One")]
        DeepOne,
        Demodand,
        Demon,
        Devil,
        Div,
        Drake,
        Dwarf,
        Earth,
        Elemental,
        Elf,
        Evil,
        Extraplanar,
        Fire,
        Giant,
        Gnome,
        Goblinoid,
        Godspawn,
        Good,
        [Display(Name = "Great Old One")]
        GreatOldOne,
        Halfling,
        Herald,
        Hive,
        Human,
        Incorporeal,
        Inevitable,
        Kaiju,
        Kami,
        Kasatha,
        Kitsune,
        Kyton,
        Lawful,
        Leshy,
        Mortic,
        Mythic,
        Native,
        Nightshade,
        Oni,
        Orc,
        Protean,
        Psychopomp,
        Qlippoth,
        Rakshasa,
        Ratfolk,
        Reptilian,
        Robot,
        Samsaran,
        Sasquatch,
        Shapechanger,
        Swarm,
        Troop,
        Udaeus,
        Unbreathing,
        Vanara,
        Vishkanya,
        Water,
        Wayang,
        [Display(Name = "Wild Hunt")]
        WildHunt,
        Wurm
    }
}