version: '3'
 
services:
  skyforger:
    image: skyforger:latest
    build:
      context:  ./skyforger
      dockerfile: Dockerfile.skyforger
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - MEGA_ID=${MEGA_ID}
      - MEGA_SECRET=${MEGA_SECRET}