namespace skyforger.models.common
{
    public enum ActionType
    {
        Null,
        Swift,
        Standard,
        Immediate,
        Move,
        Round,
        Rounds,
        FullRound,
        Second,
        Seconds,
        Minute,
        Minutes,
        Hour,
        Hours,
        Day,
        Days,
        Week,
        Weeks,
        Month,
        Months,
        Year,
        Years,
        Decade,
        Decades,
        Century,
        Centuries,
        SeeText
    }
}