name: merge

on:
  push:
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.yml'
      - '**.sln'
      - '**.json'
    branches: [ master ]

jobs:

  docker-build-deploy:

    name: Docker Build and Push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -f ./skyforger/Dockerfile.skyforger ./skyforger -t skyforger

    - name: Log into GHCR
      run: echo ${{ secrets.PAT }} | docker login ghcr.io -u luciusp --password-stdin

    - name: Tag and push image
      run: | 
        docker tag "skyforger:latest" "ghcr.io/luciusp/skyforger:$GITHUB_RUN_ID"
        docker push "ghcr.io/luciusp/skyforger:$GITHUB_RUN_ID"
        docker tag "skyforger:latest" "ghcr.io/luciusp/skyforger:latest"
        docker push "ghcr.io/luciusp/skyforger:latest" 

  deploy:

    needs: docker-build-deploy

    name: Deploy to Docker Swarm
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Register known_hosts
      run: |
        sudo mkdir ~/.ssh/
        'sudo echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts'
      env:
        KNOWN_HOSTS: ${{ secrets.DOCKER_SSH_KNOWN_HOSTS }}

    - name: Log into GHCR
      run: echo ${{ secrets.PAT }} | docker login ghcr.io -u luciusp --password-stdin

    - name: Generate Stackfile
      run: docker-compose config > stack.yml
      env:
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        ASPNETCORE_ENVIRONMENT: ${{ secrets.ASPNETCORE_ENVIRONMENT }}
        MEGA_SECRET: ${{ secrets.MEGA_SECRET }}
        AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        MEGA_ID: ${{ secrets.MEGA_ID }}

    - name: Deploy to swarm
      uses: sagebind/docker-swarm-deploy-action@v2
      with:
        remote_host: ssh://${{ secrets.REMOTE_HOST_USR }}@${{ secrets.REMOTE_HOST_IP }}
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        args: stack deploy --with-registry-auth --compose-file stack.yml skyforger